### PR TITLE
ISSUE #531 fix replicaSet connection when processing models through bouncerwrapper

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #532

#### Description
- changed raw pointer to shared_ptr so it will call the deconstructor prior to exiting

#### Test cases
- replicaset connection should no longer time out

### CODE REVIEW

**Comment by keifgwinn** [comment]
I ran this latest version but got this
```
Waiting on threads to park on joinable thread list timed out.
debugger-agent: Unable to listen on 25
Exiting batchmode successfully now!
terminate called after throwing an instance of 'boost::wrapexcept<boost::log::v2_mt_posix::system_error>'
  what():  Failed to set TLS value: Invalid argument
```

**Comment by keifgwinn** [comment]
> ```
>   what():  Failed to set TLS value: Invalid argument
> ```

It does seem to have been able to write the database refs and files

**Comment by carmenfan** [comment]
> > ```
> >   what():  Failed to set TLS value: Invalid argument
> > ```
> 
> It does seem to have been able to write the database refs and files

@keifgwinn 
This should be working now (hopefully)

However there is now a pairing update on 3drepounity https://github.com/3drepo/3drepounity/issues/416

**Comment by keifgwinn** [comment]
I've tested this and it's working

**Review by Charence — APPROVED** [review]

**Review by Charence — APPROVED** [review]

**Pull request merged**
