### PR TITLE
Issue 473 - Deployment improvements

### LINKED ISSUE #473: Improvement deployment
### Description
- reduce the size of deployment folder - only cherry pick things we need after compilation
- add some validity checks that can be optionally added in at compile time.

### Task
- [x] Add validity check
- [x] Add release packaging script
- [x] Ensure it pulls everything as needed
- [x] Add to travis to test the packaging script

### PR DESCRIPTION
**Pull request by carmenfan**
This fixes #473

#### Description
- Add ability to infuse a validity into the compiled software: When compiling cmake, add `-DVALID_UNTIL=<timestamp in seconds>` to enable this
- There is now a script that will pull in everything the bouncer needs into a single folder - you will not need anything else to run 3drepobouncerClient. The script assumes you have every env var used in compilation is set (including $BOUNCER_ROOT) See [travis changes](https://github.com/3drepo/3drepobouncer/compare/staging...ISSUE_473?expand=1#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485) for usage.

#### Test cases
- If bouncer is compiled with VALID_UNTIL, it should stop working if the current time is greater than the defined time.
- Everything should work as before.

### CODE REVIEW

**Comment by carmenfan** [comment]
2 updates:
1. the script now takes an optional dest path
2. BOUNCER_ROOT is now REPOBOUNCER_ROOT (as this is what bouncer wrapper in unity repo uses... let's make it consistent)

@keifgwinn

**Comment by keifgwinn** [comment]
Can 3drepobouncerClient reveal the current expiry time if run in help mode?

**Comment by carmenfan** [comment]
> Can 3drepobouncerClient reveal the current expiry time if run in help mode?

Yea I can add something

**Comment by keifgwinn** [comment]
would be great to see seconds and a decoded datestamp

**Comment by carmenfan** [comment]
@keifgwinn 

license validity is now shown when you probe for the version (i.e. `3drepobouncer -v`  or `3drepobouncer version`

if validity not built in:
image

if it is built in: 
image

**Pull request merged**
